# Generated by Django 4.2.7 on 2025-11-03 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(choices=[(1, '⭐ (1 звезда)'), (2, '⭐⭐ (2 звезды)'), (3, '⭐⭐⭐ (3 звезды)'), (4, '⭐⭐⭐⭐ (4 звезды)'), (5, '⭐⭐⭐⭐⭐ (5 звезд)')], default=3),
        ),
    ]
