# Generated by Django 4.2.7 on 2025-11-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_city_hotel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_ru',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за ночь (€)'),
        ),
    ]
