# Generated by Django 4.2.7 on 2025-11-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0007_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='name_ru',
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название города'),
        ),
    ]
